import { getHostComponent } from 'react-native-nitro-modules';
// The view config is generated by Nitrogen and required by Fabric.
import MapViewConfig from '../../nitrogen/generated/shared/json/MapViewConfig.json';
import type { MapViewMethods, MapViewProps } from './specs/MapView.nitro';

/**
 * The raw native MapView host component bridged from the `HybridMapView` Nitro
 * HybridView. Consumers should use the higher-level `MapView` component instead.
 */
export const NativeMapView = getHostComponent<MapViewProps, MapViewMethods>(
  'MapView',
  () => MapViewConfig,
);
